version: "3"

services:
  vscode:
    build:
      context: .
      dockerfile: ./Dockerfile.vc
    container_name: vscode
    volumes:
      - ./:/config/workspace
      - vscode-config:/config
    deploy:
      resources:
        limits:
          memory: 40GB
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8443:8443
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - ollama
      - searxng
    environment:
      - TZ=America/New-York
      - PUID=1000
      - PGID=1000
      - UMASK=007
    extra_hosts:
      - host.docker.internal:host-gateway

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    tty: true
    ports:
      - 11434:11434
    deploy:
      resources:
        limits:
          memory: 40GB
        reservations:
          memory: 24G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    depends_on:
      - ollama
      - searxng
    volumes:
      - webui:/app/backend/data
    ports:
      - 3000:8080
    environment:
      - "/ollama/api=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  redis:
    container_name: redis
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    extra_hosts:
      - host.docker.internal:host-gateway

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    ports:
      - 8080:8080
    volumes:
      - ./searxng:/etc/searxng:rw
    depends_on:
      - redis
    environment:
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-searxng}:8080/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 4443:9443
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  vscode-config:
  portainer-data:
  redis-data:
  ollama:
  webui:
