FROM linuxserver/code-server

RUN apt-get update && apt-get install -y wget

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
  unzip curl wget git swig cmake htop \
  python3 python3-pip python3-opengl \
  build-essential \
  musescore3 graphviz \
  ffmpeg \
  libsdl2-dev libsdl2-image-dev \
  cuda-toolkit-11-8

COPY ./requirements/ /requirements/
RUN pip install --upgrade pip setuptools wheel
RUN pip install -r /requirements/torch-11.8.txt
RUN pip install -r /requirements/all.txt
RUN python3 -m nltk.downloader -d /usr/local/share/nltk_data all

RUN jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
